# Generated by Django 4.2.4 on 2023-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="uploadConverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
